name: Keep Streamlit Alive

on:
  schedule:
    - cron: '0 */12 * * *'  # Cada 12 horas
  workflow_dispatch:

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar dependencias
        run: |
          sudo apt update
          sudo apt install -y chromium-chromedriver
          pip install selenium

      - name: Simular visita con Selenium
        run: |
          python - <<EOF
          from selenium import webdriver
          from selenium.webdriver.chrome.service import Service
          from selenium.webdriver.chrome.options import Options
          import time

          chrome_options = Options()
          chrome_options.add_argument("--headless")
          chrome_options.add_argument("--no-sandbox")
          chrome_options.add_argument("--disable-dev-shm-usage")

          service = Service("/usr/bin/chromedriver")
          driver = webdriver.Chrome(service=service, options=chrome_options)

          driver.get("https://ali-hop.streamlit.app/")  
          print("Página visitada con éxito")
          driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
          time.sleep(10)
          driver.execute_script("window.scrollTo(0, 0);")
          time.sleep(60)
          driver.quit()
          EOF
