[theme]
primaryColor="#9E1D20"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#31333F"
font="monospace"

[client]
showSidebarNavigation = false

[server]
headless = true
port = 8501
base = "light"
enableCORS = false

[browser]
serverAddress = "0.0.0.0"