[lottie]
url = "https://lottie.host/0461e731-e5b6-4d3b-9040-6e8216a8f1f2/wBkBsgLnEj.json"
[connections.neon]
url = 'postgresql://alimentos_owner:npg_7jvcfZHURl6q@ep-polished-hall-abmfbmvs-pooler.eu-west-2.aws.neon.tech/alimentos?sslmode=require'